// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsLogistic.Infrastructure.Persistence.PersistenceModel;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MsLogistic.Infrastructure.Migrations
{
    [DbContext(typeof(PersistenceDbContext))]
    [Migration("20251030054820_GeneralMigration")]
    partial class GeneralMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.CustomerPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryPersonPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("delivery_persons");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryZonePersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Polygon>("Boundaries")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("boundaries");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeliveryPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_person_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.ToTable("delivery_zones");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderDeliveryPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("DeliveryPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_person_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("location");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_deliveries");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderItemPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<Point>("DeliveryLocation")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("delivery_location");

                    b.Property<int?>("DeliverySequence")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_sequence");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTime>("ScheduledDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_delivery_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RouteId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.ProductPersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RoutePersistenceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DeliveryPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_person_id");

                    b.Property<Guid>("DeliveryZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_zone_id");

                    b.Property<Point>("OriginLocation")
                        .IsRequired()
                        .HasColumnType("geography")
                        .HasColumnName("origin_location");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryZonePersistenceModel", b =>
                {
                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryPersonPersistenceModel", "DeliveryPerson")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId");

                    b.Navigation("DeliveryPerson");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderDeliveryPersistenceModel", b =>
                {
                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryPersonPersistenceModel", "DeliveryPerson")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderPersistenceModel", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPerson");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderItemPersistenceModel", b =>
                {
                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderPersistenceModel", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.ProductPersistenceModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderPersistenceModel", b =>
                {
                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.CustomerPersistenceModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RoutePersistenceModel", "Route")
                        .WithMany("Orders")
                        .HasForeignKey("RouteId");

                    b.Navigation("Customer");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RoutePersistenceModel", b =>
                {
                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryPersonPersistenceModel", "DeliveryPerson")
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId");

                    b.HasOne("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.DeliveryZonePersistenceModel", "DeliveryZone")
                        .WithMany()
                        .HasForeignKey("DeliveryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryPerson");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.OrderPersistenceModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MsLogistic.Infrastructure.Persistence.PersistenceModel.EFCoreEntities.RoutePersistenceModel", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
